default_language_version.python = "3.14"

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
  { id = "check-toml" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.1"
hooks = [
  { id = "ruff-check", args = ["--fix", "--show-fixes"] },
  { id = "ruff-format" },
]
